/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class ABTableView, NSString;

// Not exported
@interface ABTableViewCell : NSView
{
    NSString *reusableIdentifier;
    ABTableView *tableView;
    long long row;
    BOOL providingMomentum;
}

- (id)initWithReusableCellIdentifier:(id)arg1;
- (void)dealloc;
- (id)reusableIdentifier;
@property(readonly, nonatomic) BOOL selected;
- (BOOL)isFlipped;
- (void)mouseDown:(id)arg1;
- (void)selectedStateDidChange;
- (void)scrollWheel:(id)arg1;
@property BOOL providingMomentum; // @synthesize providingMomentum;
@property(nonatomic, retain) ABTableView *tableView; // @synthesize tableView;
@property(nonatomic, assign) long long row; // @synthesize row;

@end

