/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABTableViewDelegate
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRow:(long long)arg2;
- (int)tableView:(id)arg1 heightForRow:(int)arg2;

@optional
- (void)tableView:(id)arg1 didSelectRow:(int)arg2;
@end

