/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class ABNavigationController, ABNavigationItem, NSView;

// Not exported
@interface ABViewController : NSResponder
{
    NSView *view;
    ABNavigationItem *navigationItem;
    ABViewController *parentViewController;
}

- (id)init;
- (void)dealloc;
- (id)initWithNibNamed:(id)arg1 bundle:(id)arg2;
@property(retain, nonatomic) NSView *view; // @synthesize view;
@property(readonly, nonatomic) NSView *_view;
- (BOOL)isEqual:(id)arg1;
- (id)nibName;
- (void)_loadViewFromNib;
- (void)loadView;
- (void)viewDidLoad;
@property(readonly, nonatomic) ABNavigationItem *navigationItem; // @synthesize navigationItem;
@property(readonly, nonatomic) ABNavigationController *navigationController;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (id)nextResponder;
- (BOOL)acceptsFirstResponder;
@property(nonatomic, retain) ABViewController *parentViewController; // @synthesize parentViewController;

@end

