/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABViewController.h"

#import "ABTableViewDelegate-Protocol.h"

@class ABTableView, NSArray, TweetieFilterBar, TwitterAccount;

// Not exported
@interface TweetieStatusListViewController : ABViewController <ABTableViewDelegate>
{
    TwitterAccount *account;
    ABTableView *tableView;
    NSArray *statuses;
    BOOL ignoreHittingTopmostElement;
    TweetieFilterBar *filterBar;
}

- (id)init;
- (void)dealloc;
- (void)loadOlder:(id)arg1;
- (void)loadView;
- (BOOL)showFilterBar;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)displayPreferencesDidChange:(id)arg1;
- (void)setView:(id)arg1;
- (id)autosaveName;
- (id)statusForRow:(long long)arg1;
- (long long)rowForStatus:(id)arg1;
- (id)_topSavedStatusIDDefaultsKey;
- (id)_topSavedStatusIDOffsetDefaultsKey;
- (id)_selectedStatusIDDefaultsKey;
- (void)saveScrollPosition;
- (void)restoreScrollPosition;
- (void)viewWillDisappear:(BOOL)arg1;
@property(retain, nonatomic) NSArray *statuses; // @synthesize statuses;
- (long long)numberOfRowsInTableView:(id)arg1;
- (BOOL)highlightMentions;
- (BOOL)shouldAmplifyStatus:(id)arg1;
- (void)noteFreshness;
- (id)tableView:(id)arg1 cellForRow:(long long)arg2;
- (int)tableView:(id)arg1 heightForRow:(int)arg2;
- (void)tableView:(id)arg1 didSelectRow:(int)arg2;
- (void)tweetieStatusCell:(id)arg1 replyToStatus:(id)arg2;
- (void)tweetieStatusCell:(id)arg1 directMessageUser:(id)arg2;
- (void)tweetieStatusCell:(id)arg1 repostStatus:(id)arg2;
- (void)tweetieStatusCell:(id)arg1 postLinkToStatus:(id)arg2;
- (void)tweetieStatusCell:(id)arg1 toggleFavoriteForStatus:(id)arg2;
- (void)tweetieStatusCell:(id)arg1 viewOnTwitter:(id)arg2;
- (void)tweetieCell:(id)arg1 statusDetails:(int)arg2;
- (void)tweetieCell:(id)arg1 fromUserDetailsForRow:(int)arg2;
- (void)tweetieCell:(id)arg1 clickedLink:(id)arg2 inRow:(int)arg3 type:(int)arg4;
@property(readonly, nonatomic) ABTableView *tableView; // @synthesize tableView;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

