/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieTableViewCell.h"

@class NSTextFieldCell, TwitterStatus;

// Not exported
@interface TweetieStatusTableViewCell : TweetieTableViewCell
{
    TwitterStatus *status;
    NSTextFieldCell *nameCell;
    NSTextFieldCell *dateCell;
    struct CGPoint replyPoint;
    BOOL isMine;
    BOOL isFavorite;
    BOOL mentionsMe;
    BOOL amplify;
    struct {
        unsigned int downOverReplyButton;
    } _status_flags;
}

+ (void)initialize;
+ (int)heightForStatus:(id)arg1 tableWidth:(int)arg2 isMine:(BOOL)arg3 amplify:(BOOL)arg4;
- (id)initWithReusableCellIdentifier:(id)arg1;
- (void)dealloc;
- (struct CGRect)textFrame;
- (struct CGRect)replyButtonDisplayRect;
- (struct CGRect)replyButtonHitRect;
- (struct CGRect)actionRect;
- (struct CGRect)profileImageFrame;
- (struct CGRect)nameFrame;
- (struct CGRect)dateFrame;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;
- (void)_updateAttributedString;
- (void)selectedStateDidChange;
- (void)setFrame:(struct CGRect)arg1;
- (void)userDidUpdateNotification:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)menuForAction;
- (id)menuForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (struct CGPoint)replyPoint;
- (void)_reply;
- (void)_setReplyPoint;
- (void)replyToTweet:(id)arg1;
- (void)directMessageUser:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)repostTweet:(id)arg1;
- (void)copyLinkToTweet:(id)arg1;
- (void)toggleTweetFavorite:(id)arg1;
- (void)viewOnTwitter:(id)arg1;
- (void)copy:(id)arg1;
- (void)keyUp:(id)arg1;
@property(nonatomic) BOOL amplify; // @synthesize amplify;
@property(nonatomic) BOOL mentionsMe; // @synthesize mentionsMe;
@property(nonatomic) BOOL isFavorite; // @synthesize isFavorite;
@property(nonatomic) BOOL isMine; // @synthesize isMine;

@end

