/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <AppKit/AppKit.h>

@class AccountLayer, AccountTabLayer, CALayer, CAScrollLayer, NSArray, NSMutableArray, TwitterAccount;

// Not exported
@interface TweetieAccountTabsView : NSView
{
    NSArray *accounts;
    NSMutableArray *accountLayers;
    NSMutableArray *accountTabLayers;
    AccountLayer *selectedAccountLayer;
    AccountTabLayer *selectedAccountTabLayer;
    AccountLayer *highlightedAccountLayer;
    AccountTabLayer *highlightedAccountTabLayer;
    CAScrollLayer *scrollLayer;
    CALayer *extraLayer;
    CALayer *selectionNipple;
    struct CGPoint scrollPosition;
    double contentHeight;
    id delegate;
}

- (void)dealloc;
- (void)awakeFromNib;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)_updateDisplay:(BOOL)arg1;
- (void)accountDidUpdateNotification:(id)arg1;
@property(copy, nonatomic) NSArray *accounts; // @synthesize accounts;
- (void)setFrame:(struct CGRect)arg1;
- (id)_layerForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)_selectAccountTabLayer:(id)arg1 update:(BOOL)arg2;
- (void)_selectAccountTab:(int)arg1 update:(BOOL)arg2;
- (void)_selectAccountLayer:(id)arg1 speedy:(BOOL)arg2;
- (void)selectNextAccount;
- (void)selectPreviousAccount;
- (void)selectAccountTab:(int)arg1;
- (void)mouseUp:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)scrollWheel:(id)arg1;
@property(readonly, nonatomic) TwitterAccount *selectedAccount;
@property(readonly, nonatomic) int selectedAccountTab;

@end

