/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

@class ABActiveTextRenderer;

// Not exported
@interface TweetieTableViewCell : ABTableViewCell
{
    ABActiveTextRenderer *activeTextRenderer;
    long long selectionAnchor;
    long long selectionEnd;
    struct _NSRange mouseDownRange;
    id delegate;
    struct {
        unsigned int downOverProfileImage;
    } _flags;
}

+ (void)initialize;
- (id)initWithReusableCellIdentifier:(id)arg1;
- (void)dealloc;
- (id)activeTextRenderer;
- (struct _NSRange)selectedRange;
- (void)clearSelection;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)selectAll:(id)arg1;
- (struct CGRect)textFrame;
- (struct CGRect)profileImageFrame;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (long long)_characterIndexForEvent:(id)arg1;
- (struct _NSRange)_rangeForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)triggerDelegateStatusDetails;
- (void)mouseUp:(id)arg1;
- (void)fixTrackingAreas;
- (void)setFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic, assign) id delegate; // @synthesize delegate;

@end

