/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class ABActiveTextRanges, NSDate, NSString, NSURL, TwitterUser;

// Not exported
@interface TwitterStatus : NSObject
{
    NSString *statusID;
    NSString *text;
    ABActiveTextRanges *activeTextRanges;
    NSDate *date;
    NSString *originalDateString;
    TwitterUser *fromUser;
    NSString *inReplyToStatusID;
    struct {
        unsigned int isPartialStatus:1;
        unsigned int isRead:1;
        unsigned int wasSeen:1;
        unsigned int didGlobalNotification;
    } _flags;
}

+ (id)statusWithXML:(id)arg1;
+ (id)statusesWithXML:(id)arg1;
+ (id)statusesWithSearchJSON:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (long long)compare:(id)arg1;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(nonatomic) BOOL isPartialStatus;
@property(nonatomic) BOOL isRead;
@property(nonatomic) BOOL wasSeen;
@property(readonly, nonatomic) NSURL *twitterURL;
- (BOOL)isNotADummyStatus;
@property(nonatomic) BOOL didGlobalNotification;
@property(copy, nonatomic) NSString *inReplyToStatusID; // @synthesize inReplyToStatusID;
@property(copy, nonatomic) NSString *originalDateString; // @synthesize originalDateString;
@property(retain, nonatomic) TwitterUser *fromUser; // @synthesize fromUser;
@property(copy, nonatomic) NSDate *date; // @synthesize date;
@property(copy, nonatomic) NSString *statusID; // @synthesize statusID;
@property(readonly, nonatomic) ABActiveTextRanges *activeTextRanges; // @synthesize activeTextRanges;

@end

