/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSDate, NSMutableArray, NSMutableSet, NSString, TwitterDirectMessagesConversationManager, TwitterRepliesStream, TwitterTimelineStream, TwitterUser;

// Not exported
@interface TwitterAccount : NSObject
{
    NSString *username;
    NSString *password;
    NSString *oAuthToken;
    NSString *oAuthTokenSecret;
    BOOL needToSavePassword;
    TwitterUser *user;
    TwitterTimelineStream *timelineStream;
    TwitterRepliesStream *repliesStream;
    TwitterDirectMessagesConversationManager *directMessagesManager;
    NSMutableSet *favoritesSet;
    NSMutableArray *savedSearches;
    struct {
        unsigned int loadingUser:1;
    } _flags;
    unsigned long long notificationOptions;
    NSDate *freshTweets;
    NSDate *freshMentions;
    NSDate *freshMessages;
    NSDate *freshSearches;
}

- (id)init;
- (id)initWithUsername:(id)arg1 password:(id)arg2;
- (void)verifyCredentialsWithXAuth:(id)arg1;
- (void)verifyCredentialsWithXAuthResponse:(id)arg1 info:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)keychainService;
@property(nonatomic) unsigned long long notificationOptions; // @synthesize notificationOptions;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)refreshViaPolling;
- (void)refresh;
@property(copy, nonatomic) NSString *password; // @synthesize password;
- (long long)compare:(id)arg1;
@property(readonly, nonatomic) TwitterUser *user;
- (void)_postAccountDidUpdateNotification;
- (void)myUserResponse:(id)arg1 info:(id)arg2;
- (void)myUserDidUpdate:(id)arg1;
- (id)request:(id)arg1;
- (id)authenticatedRequest:(id)arg1;
- (void)verifyCredentials:(id)arg1;
- (id)cachedUserWithID:(id)arg1;
- (id)cachedUserWithUsername:(id)arg1;
- (id)cachedStatusWithID:(id)arg1;
- (void)requestUserWithID:(id)arg1 callback:(id)arg2;
- (void)unauthenticatedUserForIDResponse:(id)arg1 info:(id)arg2;
- (void)authenticatedUserForIDResponse:(id)arg1 info:(id)arg2;
- (void)requestCurrentUserWithCallback:(id)arg1;
- (void)requestUserWithUsername:(id)arg1 callback:(id)arg2;
- (void)unauthenticatedUserForUsernameResponse:(id)arg1 info:(id)arg2;
- (void)authenticatedUserForUsernameResponse:(id)arg1 info:(id)arg2;
- (void)requestStatusWithID:(id)arg1 callback:(id)arg2;
- (void)unauthenticatedStatusResponse:(id)arg1 info:(id)arg2;
- (void)authenticatedStatusResponse:(id)arg1 info:(id)arg2;
- (id)timelineStream;
- (id)repliesStream;
- (id)directMessagesManager;
- (void)sendDirectMessage:(id)arg1 to:(id)arg2 callback:(id)arg3;
- (void)didMessage:(id)arg1 info:(id)arg2;
- (void)update:(id)arg1 inReplyToStatusID:(id)arg2 callback:(id)arg3;
- (void)didUpdate:(id)arg1 info:(id)arg2;
- (BOOL)isAuthorOfStatus:(id)arg1;
- (BOOL)isAuthorOfDirectMessage:(id)arg1;
- (BOOL)isMentionedInStatus:(id)arg1;
- (void)addStatusToFavorites:(id)arg1;
- (BOOL)isFavoriteStatus:(id)arg1;
- (id)savedSearches;
- (BOOL)containsSavedSearch:(id)arg1;
- (void)addSavedSearch:(id)arg1;
- (void)removeSavedSearch:(id)arg1;
- (BOOL)hasFreshTweets;
- (BOOL)hasFreshMentions;
- (BOOL)hasFreshMessages;
- (BOOL)hasFreshSearches;
- (BOOL)hasFreshAnythingApplicableToStatusItem;
- (BOOL)hasFreshAnythingApplicableToDockBadge;
- (void)markAllAsRead;
- (void)noteFreshTweets;
- (void)noteFreshMentions;
- (void)noteFreshMessages;
- (void)noteFreshSearches;
- (id)unNotifiedStatuses:(id)arg1;
- (void)somethingDidUpdate:(id)arg1;
- (void)checkIfUser:(id)arg1 follows:(id)arg2 callback:(id)arg3;
- (void)followingStatus:(id)arg1 info:(id)arg2;
- (void)follow:(id)arg1 callback:(id)arg2;
- (void)stopFollowing:(id)arg1 callback:(id)arg2;
@property(copy, nonatomic) NSString *oAuthTokenSecret; // @synthesize oAuthTokenSecret;
@property(copy, nonatomic) NSString *oAuthToken; // @synthesize oAuthToken;
@property(copy, nonatomic) NSString *username; // @synthesize username;

@end

