/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class ABCallback, TwitterAccount;

// Not exported
@interface TwitterAPI : NSObject
{
    TwitterAccount *authenticateWithAccount;
    ABCallback *responseCallback;
}

+ (id)authenticatedRequest:(id)arg1 callback:(id)arg2;
+ (id)request:(id)arg1;
- (id)initWithAccount:(id)arg1 callback:(id)arg2;
- (void)dealloc;

@end

